### PR TITLE
Feature/add pgmbasico02

### PR DESCRIPTION
**Pull request by habolanos**
Add PGM to print a sheet and use a thread for simulate a wait for print on Java program

Check it:
image

### CODE REVIEW

**Comment by santiagodc8** [comment]
ok

**Review by santiagodc8 — APPROVED** [review]
ok

**Review by cesarlarboleda — APPROVED** [review]

**Review by JHBorrero — APPROVED** [review]

**Comment by Juanquijanop** [comment]
Nice 🚀

**Review by Juanquijanop — APPROVED** [review]
Nice 🚀📈

**Review by LuisFCaicedo — APPROVED** [review]

**Pull request merged**
